
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:3 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/home/GyroPower/appsRepos/Vulkan_SDK/1.4.341.1/x86_64/bin/"
      - "/home/GyroPower/appsRepos/emscripten/emsdk/"
      - "/home/GyroPower/appsRepos/emscripten/emsdk/upstream/emscripten/"
      - "/home/GyroPower/.local/share/pipx/venvs/conan/bin/"
      - "/home/GyroPower/.conan2/p/b/libngc10436b18b121/p/bin/"
      - "/home/GyroPower/.dotnet/tools/"
      - "/home/GyroPower/Documents/netcoredbg/"
      - "/home/GyroPower/.local/share/nvim/mason/bin/"
      - "/usr/local/sbin/"
      - "/usr/local/bin/"
      - "/usr/bin/"
      - "/home/GyroPower/.local/share/flatpak/exports/bin/"
      - "/var/lib/flatpak/exports/bin/"
      - "/usr/lib/jvm/default/bin/"
      - "/opt/llvm-mingw/bin/"
      - "/usr/bin/site_perl/"
      - "/usr/bin/vendor_perl/"
      - "/usr/bin/core_perl/"
      - "/usr/lib/rustup/bin/"
      - "/bin/"
    searched_directories:
      - "/home/GyroPower/appsRepos/Vulkan_SDK/1.4.341.1/x86_64/bin/uname"
      - "/home/GyroPower/appsRepos/emscripten/emsdk/uname"
      - "/home/GyroPower/appsRepos/emscripten/emsdk/upstream/emscripten/uname"
      - "/home/GyroPower/.local/share/pipx/venvs/conan/bin/uname"
      - "/home/GyroPower/.conan2/p/b/libngc10436b18b121/p/bin/uname"
      - "/home/GyroPower/.dotnet/tools/uname"
      - "/home/GyroPower/Documents/netcoredbg/uname"
      - "/home/GyroPower/.local/share/nvim/mason/bin/uname"
      - "/usr/local/sbin/uname"
      - "/usr/local/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/home/GyroPower/appsRepos/Vulkan_SDK/1.4.341.1/x86_64/bin"
        - "/home/GyroPower/appsRepos/emscripten/emsdk"
        - "/home/GyroPower/appsRepos/emscripten/emsdk/upstream/emscripten"
        - "/home/GyroPower/.local/share/pipx/venvs/conan/bin/"
        - "/home/GyroPower/.conan2/p/b/libngc10436b18b121/p/bin/"
        - "/home/GyroPower/.dotnet/tools"
        - "/home/GyroPower/Documents/netcoredbg"
        - "/home/GyroPower/.local/share/nvim/mason/bin"
        - "/home/GyroPower/appsRepos/Vulkan_SDK/1.4.341.1/x86_64/bin"
        - "/usr/local/sbin"
        - "/usr/local/bin"
        - "/usr/bin"
        - "/home/GyroPower/.local/share/flatpak/exports/bin"
        - "/var/lib/flatpak/exports/bin"
        - "/usr/lib/jvm/default/bin"
        - "/opt/llvm-mingw/bin"
        - "/usr/bin/site_perl"
        - "/usr/bin/vendor_perl"
        - "/usr/bin/core_perl"
        - "/usr/lib/rustup/bin"
...
